/* Math Operations in Javascript */
console.log(10 + 2)
console.log(10 - 2)
console.log(10 * 2)
console.log(10 / 2)
console.log(10 % 2)
console.log(10 ** 2)

/* Math object */
console.log(Math.PI)
console.log(Math.SQRT2)
console.log(Math.E)
console.log(Math.sqrt(2))
console.log(Math.pow(2,3))
console.log(Math.floor(2.4))
console.log(Math.floor(2.9999999999999999))
console.log(Math.floor(-2.4))
console.log(Math.ceil(2.2))
console.log(Math.ceil(-2.9))
console.log(Math.round(2.1))
console.log(Math.round(2.5))
console.log(Math.round(2.7))
console.log(Math.round(-2.1))
console.log(Math.round(-2.9))
console.log(Math.random()) // Returns value between 0 and 1
console.log(Math.floor(Math.random() * 21))
console.log(8/0)
console.log(-8/0)
console.log(typeof  Infinity)
console.log(0/0)
console.log(typeof NaN)
